server:
  port: 9999
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/properties/
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.222:8000/eureka/

